# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb7b1e33e4a294b68874314adf6e69c60401a603893c01a1ee9ec7733678fd2721db0065409595c87f71b6204b478cfa88d7393bab987b3a64dee819035ee43

test:
  secret_key_base: b7d19d9156ca73e1903591e5f0343823a53980bdb806f7fc22c722aaa2b2cb475eb165d1695e2dd02740f1b172d5ffd1f83684282883e427e493b793172febbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
